/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AttachmentDropzone: typeof import('./src/modules/core/components/Form/AttachmentDropzone.vue')['default']
    AvatarPicker: typeof import('./src/modules/core/components/Form/AvatarPicker.vue')['default']
    BaseForm: typeof import('./src/modules/core/components/Form/BaseForm.vue')['default']
    BlockInfo: typeof import('./src/modules/core/components/BlockInfo.vue')['default']
    ColorPicker: typeof import('./src/modules/core/components/Form/ColorPicker.vue')['default']
    ConfirmDialog: typeof import('./src/modules/core/components/Dialogs/ConfirmDialog.vue')['default']
    DatePicker: typeof import('./src/modules/core/components/Form/DatePicker.vue')['default']
    DateTimePicker: typeof import('./src/modules/core/components/Form/DateTimePicker.vue')['default']
    DropdownBulkActions: typeof import('./src/modules/core/components/Table/DropdownBulkActions.vue')['default']
    FormLanguageSwitcher: typeof import('./src/modules/core/components/Form/FormLanguageSwitcher.vue')['default']
    JsonViewer: typeof import('./src/modules/core/components/JsonViewer.vue')['default']
    MinutesView: typeof import('./src/modules/core/components/MinutesView.vue')['default']
    Money: typeof import('./src/modules/core/components/Money.vue')['default']
    PageLoader: typeof import('./src/modules/core/components/PageLoader.vue')['default']
    PageStateWrapper: typeof import('./src/modules/core/components/PageStateWrapper.vue')['default']
    ProfilePhotoPicker: typeof import('./src/modules/core/components/Form/ProfilePhotoPicker.vue')['default']
    RoleBadge: typeof import('./src/modules/core/components/RoleBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SmartDataTable: typeof import('./src/modules/core/components/Table/SmartDataTable.vue')['default']
    TableActiveStatus: typeof import('./src/modules/core/components/Table/Partials/TableActiveStatus.vue')['default']
    TableAgent: typeof import('./src/modules/core/components/Table/Partials/TableAgent.vue')['default']
    TableBadge: typeof import('./src/modules/core/components/Table/Partials/TableBadge.vue')['default']
    TableBoolean: typeof import('./src/modules/core/components/Table/Partials/TableBoolean.vue')['default']
    TableEnum: typeof import('./src/modules/core/components/Table/Partials/TableEnum.vue')['default']
    TableFilters: typeof import('./src/modules/core/components/Table/TableFilters.vue')['default']
    TableHeader: typeof import('./src/modules/core/components/Table/TableHeader.vue')['default']
    TableHeaderActions: typeof import('./src/modules/core/components/Table/TableHeaderActions.vue')['default']
    TableMinutes: typeof import('./src/modules/core/components/Table/Partials/TableMinutes.vue')['default']
    TableMoney: typeof import('./src/modules/core/components/Table/Partials/TableMoney.vue')['default']
    TablePagination: typeof import('./src/modules/core/components/Table/TablePagination.vue')['default']
    TableRowActions: typeof import('./src/modules/core/components/Table/TableRowActions.vue')['default']
    TableStatus: typeof import('./src/modules/core/components/Table/Partials/TableStatus.vue')['default']
    TableThumbnail: typeof import('./src/modules/core/components/Table/Partials/TableThumbnail.vue')['default']
    TableUserInfo: typeof import('./src/modules/core/components/Table/Partials/TableUserInfo.vue')['default']
    TimePicker: typeof import('./src/modules/core/components/Form/TimePicker.vue')['default']
    TimePickerPro: typeof import('./src/modules/core/components/Form/TimePickerPro.vue')['default']
  }
}
