<?php

namespace Modules\User\Enums;

use Modules\Support\Traits\EnumArrayable;

enum PermissionAction: string
{
    use EnumArrayable;

    case Index = "index";
    case Show = "show";
    case Create = "create";
    case Edit = "edit";
    case Destroy = "destroy";
    case markAsReceived = "mark_as_received";
    case Analytics = "analytics";
    case Viewer = "viewer";
    case Open = "open";
    case Close = "close";
    case Cancel = "cancel";
    case Submit = "submit";
    case Approve = "approve";
    case Reject = "reject";
    case ManualAdjust = "manual_adjust";
    case Lock = "lock";
    case Unlock = "unlock";
    case OverrideLocked = "override_locked";
    case Refund = "refund";
    case Active = "active";
    case Upcoming = "upcoming";
    case ReceivePayment = "receive_payment";
    case UpdateStatus = "update_status";
    case AssignWaiter = "assign_waiter";
    case Merge = "merge";
    case Split = "split";
    case TotalSales = "total_sales";
    case TotalOrders = "total_orders";
    case TotalActiveOrders = "total_active_orders";
    case AverageOrderValue = "average_order_value";
    case TotalUsers = "total_users";
    case TotalMenus = "total_menus";
    case TotalProducts = "total_products";
    case TotalCategories = "total_categories";
    case SalesAnalytics = "sales_analytics";
    case  BestPerformingBranches = "best_performing_branches";
    case  OrderTypeDistribution = "order_type_distribution";
    case  OrderTotalByStatus = "order_total_by_status";
    case  PaymentsOverview = "payments_overview";
    case  BranchWiseSalesComparison = "branch_wise_sales_comparison";
    case  CashMovementsOverview = "cash_movements_overview";
    case  TopSellingProducts = "top_selling_products";
    case  LowStockAlerts = "low_stock_alerts";
    case  Sales = "sales";
    case ProductsPurchase = "products_purchase";
    case Tax = "tax";
    case BranchPerformance = "branch_performance";
    case Payments = "payments";
    case DiscountsAndVouchers = "discounts_and_vouchers";
    case ProductTax = "product_tax";
    case IngredientUsage = "ingredient_usage";
    case RegisterSummary = "register_summary";
    case CashMovement = "cash_movement";
    case SalesByCreator = "sales_by_creator";
    case SalesByCashier = "sales_by_cashier";
    case Financials = "financials";
    case KitchenViewer = "kitchen_viewer";
    case CategorizedProducts = "categorized_products";
    case UpcomingOrders = "upcoming_orders";
    case CostAndRevenueByOrder = "cost_and_revenue_by_order";
    case CostAndRevenueByProduct = "cost_and_revenue_by_product";
    case IndexRewards = "index_rewards";
    case Redeem = "redeem";
    case AvailableGifts = "available_gifts";
    case Print = "print";
    case Reopen = "reopen";

    case LoyaltyLastActivity = "loyalty_last_activity";
    case LoyaltyInactiveCustomers = "loyalty_inactive_customers";
    case LoyaltyNoRedemptions = "loyalty_no_redemptions";
    case LoyaltyTopCustomersByPoints = "loyalty_top_customers_by_points";
    case LoyaltyProgramSummary = "loyalty_program_summary";
    case LoyaltyTotalEarnedPoints = "loyalty_total_earned_points";
    case LoyaltyTotalRedeemedPoints = "loyalty_total_redeemed_points";
    case LoyaltyTotalExpiredPoints = "loyalty_total_expired_points";
    case LoyaltySystemPointsBalance = "loyalty_system_points_balance";
    case LoyaltyRedemptionRate = "loyalty_redemption_rate";
    case LoyaltyAveragePointsPerProgram = "loyalty_average_points_per_program";
    case LoyaltyPointsLifecycleTimeline = "loyalty_points_lifecycle_timeline";
    case loyaltyTierRedemptionRate = "loyalty_tier_redemption_rate";
    case LoyaltyTierCustomerDistribution = "loyalty_tier_customer_distribution";
    case LoyaltyMostRedeemedRewards = "loyalty_most_redeemed_rewards";
    case LoyaltyLeastUsedRewards = "loyalty_least_used_rewards";
    case LoyaltyNeverRedeemedRewards = "loyalty_never_redeemed_rewards";
    case LoyaltyRewardsByType = "loyalty_rewards_by_type";
    case LoyaltyRewardsByTier = "loyalty_rewards_by_tier";
    case LoyaltyRewardsByProgram = "loyalty_rewards_by_program";
    case LoyaltyAvailableGifts = "loyalty_available_gifts";
    case LoyaltyUsedGifts = "loyalty_used_gifts";
    case LoyaltyExpiredGifts = "loyalty_expired_gifts";
    case LoyaltyGiftUsageRate = "loyalty_gift_usage_rate";
    case LoyaltyUnusedGiftsPerCustomer = "loyalty_unused_gifts_per_customer";
    case LoyaltyRedemptionsByStatus = "loyalty_redemptions_by_status";
    case LoyaltyRedemptionsByProgram = "loyalty_redemptions_by_program";
    case LoyaltyAveragePointsPerRedemption = "loyalty_average_points_per_redemption";
    case LoyaltyActivePromotions = "loyalty_active_promotions";
    case LoyaltyExpiredPromotions = "loyalty_expired_promotions";
    case LoyaltyPromotionUsage = "loyalty_promotion_usage";
    case LoyaltyHighestImpactPromotions = "loyalty_highest_impact_promotions";
    case LoyaltyBonusVsMultiplierComparison = "loyalty_bonus_vs_multiplier_comparison";
    case LoyaltyCategoryBoostPromotions = "loyalty_category_boost_promotions";
    case LoyaltyNewMemberPromotions = "loyalty_new_member_promotions";
    case LoyaltyAverageOrderValueLoyaltyCustomers = "loyalty_average_order_value_loyalty_customers";
    case LoyaltyRevenueFromLoyaltyCustomers = "loyalty_revenue_from_loyalty_customers";
    case LoyaltyRevenueBeforeAfterLoyalty = "loyalty_revenue_before_after_loyalty";
    case LoyaltyFreeItemsCost = "loyalty_free_items_cost";
    case GiftCardSales = "gift_card_sales";
    case GiftCardRedemption = "gift_card_redemption";
    case GiftCardOutstandingBalance = "gift_card_outstanding_balance";
    case GiftCardLiability = "gift_card_liability";
    case GiftCardExpiry = "gift_card_expiry";
    case GiftCardTransactions = "gift_card_transactions";
    case GiftCardBranchPerformance = "gift_card_branch_performance";
    case GiftCardBatch = "gift_card_batch";
    case Download = "download";
    case Recalculate = "recalculate";
    case Export = "export";
    case Backup = "backup";
    case Restore = "restore";

}
