<?php
return [
    "reports" => "Reports",
    "report" => "Report",

    "filters" => [
        "start_date" => "Start Date",
        "end_date" => "End Date",
        "order_status" => "Order Status",
        "order_type" => "Order Type",
        "payment_status" => "Payment Status",
        "product_name" => "Product Name",
        "payment_method" => "Payment Method",
        "sold_by" => "Sold By",
        "cashier" => "Cashier",
        "card_code" => "Card Code",
        "user" => "User",
        "expiry_from" => "Expiry From",
        "expiry_to" => "Expiry To",
        "reason" => "Reason",
        "direction" => "Direction",
        "menu" => "Menu",
        "discount_type" => "Discount Type",
        "created_by" => "Created By",
    ],

    "groups" => [
        "restaurant_sales_reports" => "Restaurant Sales Reports",
        "inventory_reports" => "Inventory Reports",
        "pos_reports" => "POS Reports",
        "gift_card_reports" => "Gift Card Reports",
        "system_reports" => "System Reports",
        "loyalty_overview_reports" => "Loyalty Overview Reports",
        "loyalty_customer_reports" => "Loyalty Customer Reports",
        "loyalty_tier_reports" => "Loyalty Tier Reports",
        "loyalty_rewards_reports" => "Loyalty Rewards Reports",
        "loyalty_gifts_reports" => "Loyalty Gifts Reports",
        "loyalty_redemptions_reports" => "Loyalty Redemptions Reports",
        "loyalty_promotions_reports" => "Loyalty Promotions Reports",
        "loyalty_financial_roi_reports" => "Loyalty Financial & ROI Reports"
    ],

    "definitions" => [
        "sales" => [
            "title" => "Sales Report",
            "description" => "A detailed breakdown of sales performance within a selected time range.",
        ],

        "products_purchase" => [
            "title" => "Products Purchase Report",
            "description" => "This report helps analyze product procurement performance across different periods"
        ],

        "tax" => [
            "title" => "Tax Report",
            "description" => "Summarizes collected taxes by order status, type, and payment over a selected period."
        ],

        "branch_performance" => [
            "title" => "Branch Performance Report",
            "description" => "Shows key sales and order metrics for each branch to compare performance over time."
        ],

        "payments" => [
            "title" => "Payments Report",
            "description" => "Breaks down received payments by method to track revenue collection."
        ],

        "discounts_and_vouchers" => [
            "title" => "Discounts & Vouchers Report",
            "description" => "Shows how discounts and vouchers were redeemed, including usage counts and total discounted amounts.",
        ],
        "gift_card_sales" => [
            "title" => "Gift Card Sales Report",
            "description" => "Shows all gift cards that were sold within a selected period.",
        ],
        "gift_card_redemption" => [
            "title" => "Gift Card Redemption Report",
            "description" => "Shows all gift cards used for payment in orders.",
        ],
        "gift_card_outstanding_balance" => [
            "title" => "Gift Card Outstanding Balance Report",
            "description" => "Displays all active gift cards and their remaining balances.",
        ],
        "gift_card_liability" => [
            "title" => "Gift Card Liability Report",
            "description" => "Financial report showing the remaining liability of gift cards.",
        ],
        "gift_card_expiry" => [
            "title" => "Gift Card Expiry Report",
            "description" => "Lists gift cards that are close to expiration or already expired.",
        ],
        "gift_card_transactions" => [
            "title" => "Gift Card Transactions Report",
            "description" => "Displays all transactions related to gift cards.",
        ],
        "gift_card_branch_performance" => [
            "title" => "Gift Card Branch Performance Report",
            "description" => "Compares gift card activity across branches.",
        ],
        "gift_card_batch" => [
            "title" => "Gift Card Batch Report",
            "description" => "Shows statistics for gift card batches generated by the system.",
        ],

        "product_tax" => [
            "title" => "Product Tax Report",
            "description" => "Displays the total tax amounts applied to specific products within a selected period."
        ],

        "ingredient_usage" => [
            "title" => "Ingredient Usage Report",
            "description" => "Tracks the total quantity of each ingredient used based on sold products during a selected period"
        ],

        "low_stock_alerts" => [
            "title" => "Low Stock Alerts",
            "description" => "Identifies ingredients that are nearing depletion or already finished to prompt timely restocking."
        ],

        "register_summary" => [
            "title" => "Register Summary Report",
            "description" => "Provides a financial summary of POS registers including sessions, sales, cash movements, and balances."
        ],

        "cash_movement" => [
            "title" => "Cash Movement Report",
            "description" => "Tracks all cash-in and cash-out transactions across POS registers, including users and reasons."
        ],

        "sales_by_creator" => [
            "title" => "Sales By Creator Report",
            "description" => "Shows total sales grouped by the user who created each order, helping track individual employee performance."
        ],

        "sales_by_cashier" => [
            "title" => "Sales By Cashier Report",
            "description" => "Summarizes total sales handled by each cashier, excluding canceled and refunded orders."
        ],

        "categorized_products" => [
            "title" => "Categorized Products Report",
            "description" => "Shows each category with its total product count — ideal for reviewing product distribution."
        ],
        "upcoming_orders" => [
            "title" => "Upcoming Orders Report",
            "description" => "Displays scheduled orders that are set to be prepared or served at a future time."
        ],

        "cost_and_revenue_by_order" => [
            "title" => "Cost & Revenue Report by Order",
            "description" => "Show each order’s total cost (based on product costs), total revenue (sales), and profit."
        ],

        "cost_and_revenue_by_product" => [
            "title" => "Cost & Revenue Report by Product",
            "description" => "Provides an overview of product performance in terms of quantity sold, cost, and revenue."
        ],

        "loyalty_program_summary" => [
            "title" => "Loyalty Program Summary",
            "description" => "Overview of each loyalty program with customer count and points lifecycle totals.",
        ],

        "loyalty_total_earned_points" => [
            "title" => "Total Earned Points",
            "description" => "Total loyalty points earned within the selected period.",
        ],

        "loyalty_total_redeemed_points" => [
            "title" => "Total Redeemed Points",
            "description" => "Total loyalty points redeemed within the selected period.",
        ],

        "loyalty_total_expired_points" => [
            "title" => "Total Expired Points",
            "description" => "Total loyalty points that expired without redemption.",
        ],

        "loyalty_system_points_balance" => [
            "title" => "System Points Balance",
            "description" => "Total current points balance across active loyalty customers.",
        ],

        "loyalty_redemption_rate" => [
            "title" => "Redemption Rate",
            "description" => "Ratio of redeemed points to earned points per program.",
        ],

        "loyalty_average_points_per_program" => [
            "title" => "Average Points per Program",
            "description" => "Average points balance for customers in each program.",
        ],

        "loyalty_points_lifecycle_timeline" => [
            "title" => "Points Lifecycle Timeline",
            "description" => "Daily earned vs redeemed vs expired points across loyalty programs.",
        ],

        "loyalty_last_activity" => [
            "title" => "Last Loyalty Activity",
            "description" => "Latest loyalty activity per customer with last earn/redeem timestamps.",
        ],

        "loyalty_inactive_customers" => [
            "title" => "Inactive Loyalty Customers",
            "description" => "Customers with no loyalty activity recently and their inactivity duration.",
        ],

        "loyalty_no_redemptions" => [
            "title" => "Customers with No Redemptions",
            "description" => "Customers who have never redeemed loyalty points.",
        ],

        "loyalty_top_customers_by_points" => [
            "title" => "Top Customers by Points",
            "description" => "Customers ranked by lifetime points and current balance.",
        ],

        "loyalty_top_customers_by_spend" => [
            "title" => "Top Customers by Spend",
            "description" => "Loyalty customers ranked by total spend and orders.",
        ],

        "loyalty_top_customers_by_orders" => [
            "title" => "Top Customers by Orders",
            "description" => "Loyalty customers ranked by total orders and average order value.",
        ],

        "loyalty_tier_customer_distribution" => [
            "title" => "Customers by Tier Distribution",
            "description" => "How loyalty customers are distributed across tiers.",
        ],

        "loyalty_tier_redemption_rate" => [
            "title" => "Redemption Rate per Tier",
            "description" => "Earned vs redeemed points segmented by tier.",
        ],

        "loyalty_most_redeemed_rewards" => [
            "title" => "Most Redeemed Rewards",
            "description" => "Rewards with the highest redemption count.",
        ],

        "loyalty_least_used_rewards" => [
            "title" => "Least Used Rewards",
            "description" => "Rewards with minimal redemption counts.",
        ],

        "loyalty_never_redeemed_rewards" => [
            "title" => "Never Redeemed Rewards",
            "description" => "Rewards that were never redeemed.",
        ],

        "loyalty_rewards_by_type" => [
            "title" => "Rewards by Type",
            "description" => "Rewards grouped by type with redemption totals.",
        ],

        "loyalty_rewards_by_tier" => [
            "title" => "Rewards by Tier",
            "description" => "Rewards available per loyalty tier.",
        ],

        "loyalty_rewards_by_program" => [
            "title" => "Rewards by Program",
            "description" => "Rewards grouped by loyalty program.",
        ],

        "loyalty_available_gifts" => [
            "title" => "Available Gifts",
            "description" => "Gifts that are available for use.",
        ],

        "loyalty_used_gifts" => [
            "title" => "Used Gifts",
            "description" => "Gifts that have been redeemed.",
        ],

        "loyalty_expired_gifts" => [
            "title" => "Expired Gifts",
            "description" => "Gifts that expired unused.",
        ],

        "loyalty_gift_usage_rate" => [
            "title" => "Gift Usage Rate",
            "description" => "Usage rate of issued gifts.",
        ],

        "loyalty_unused_gifts_per_customer" => [
            "title" => "Unused Gifts per Customer",
            "description" => "Unused gifts grouped by customer.",
        ],

        "loyalty_redemptions_by_status" => [
            "title" => "Redemptions by Status",
            "description" => "Redemptions grouped by status.",
        ],

        "loyalty_redemptions_by_program" => [
            "title" => "Redemptions by Program",
            "description" => "Redemptions grouped by loyalty program.",
        ],

        "loyalty_average_points_per_redemption" => [
            "title" => "Average Points per Redemption",
            "description" => "Average points spent per redemption.",
        ],

        "loyalty_active_promotions" => [
            "title" => "Active Promotions",
            "description" => "Currently active promotions.",
        ],

        "loyalty_expired_promotions" => [
            "title" => "Expired Promotions",
            "description" => "Promotions that ended.",
        ],

        "loyalty_promotion_usage" => [
            "title" => "Promotion Usage",
            "description" => "Usage count per promotion.",
        ],

        "loyalty_highest_impact_promotions" => [
            "title" => "Highest Impact Promotions",
            "description" => "Promotions with highest points generated.",
        ],

        "loyalty_bonus_vs_multiplier_comparison" => [
            "title" => "Bonus vs Multiplier Comparison",
            "description" => "Compares bonus and multiplier promotions.",
        ],

        "loyalty_category_boost_promotions" => [
            "title" => "Category Boost Promotions",
            "description" => "Promotions boosting specific categories.",
        ],

        "loyalty_new_member_promotions" => [
            "title" => "New Member Promotions",
            "description" => "Promotions for new loyalty members.",
        ],

        "loyalty_free_items_cost" => [
            "title" => "Free Items Cost",
            "description" => "Cost of free items issued.",
        ],

        "loyalty_revenue_from_loyalty_customers" => [
            "title" => "Revenue from Loyalty Customers",
            "description" => "Revenue generated by loyalty customers.",
        ],

        "loyalty_revenue_before_after_loyalty" => [
            "title" => "Revenue Before vs After Loyalty",
            "description" => "Revenue comparison for loyalty vs non-loyalty orders.",
        ],

        "loyalty_average_order_value_loyalty_customers" => [
            "title" => "Average Order Value (Loyalty Customers)",
            "description" => "Average order value for loyalty customers.",
        ],
    ],
    "export_failed" => "Export failed. Please try again later."
];
